name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start dev server in background
        run: npm run dev &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests headless
        run: npx cypress run


        
